### ISSUE TITLE
Make use of Request

### ISSUE THREAD

**Issue by beanmoss** [markheramis/EnventOS#5]
https://github.com/markheramis/EnventOS/blob/b39648fb78e595ccc7769e5e866f3906c27585bb/app/Http/Requests/Request.php#L7

Make use of this, very handy for [validation](https://laravel.com/docs/5.2/validation#other-validation-approaches) etc..

**Comment by markheramis** [comment]
Yes, i'm preparing to use FormRequest for all my controller functions in here

https://github.com/markheramis/EnventOS/tree/dev/validation

but for some reason, when I was trying out some things from the internet

when I set this to false

https://github.com/markheramis/EnventOS/blob/test/validation/app/Http/Requests/customerGetAllRequest.php#L18

I see an error 500 instead of error 403

**Comment by beanmoss** [comment]
I suggest you isolate the issue. You can have a separate Laravel installation just to test "things from the internet" stuffs. Be sure that those example snippets match the current version of your Laravel installation. API might change within different versions. Also, see to it that APP_DEBUG is set to true during development. Look for the PHP/apache/nginx log config as to where those directories are.

**Comment by markheramis** [comment]
Hello,
I solved the issue i was getting related to that `error 500` at  https://github.com/markheramis/EnventOS/commit/2aee29dfe2ea034d63e2ad76930cf3a742122e1c thank you for your guidance.
